const FILE_LIST = [
  {
    filename:
      "samples/0000_p001-folder_000/0_p001-folder_000_g2_5_s0_Grip_the_string_of_the_button_envelope.jsonl",
    scene: "p001-folder",
    sequence: "000",
    text: "Grip the string of the button envelope",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 0,
    seed: 1234,
  },
  {
    filename:
      "samples/0000_p001-folder_000/0_p001-folder_000_g2_5_s1_Grip_the_string_of_the_button_envelope.jsonl",
    scene: "p001-folder",
    sequence: "000",
    text: "Grip the string of the button envelope",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 1,
    seed: 1234,
  },
  {
    filename:
      "samples/0000_p001-folder_000/0_p001-folder_000_g2_5_s2_Grip_the_string_of_the_button_envelope.jsonl",
    scene: "p001-folder",
    sequence: "000",
    text: "Grip the string of the button envelope",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 2,
    seed: 1234,
  },
  {
    filename:
      "samples/0001_p003-packing_016/1_p003-packing_016_g2_5_s0_Reach_for_the_clothes_brush_to_get_ready_for_scrubbing_the_T-shirt_.jsonl",
    scene: "p003-packing",
    sequence: "016",
    text: "Reach for the clothes brush to get ready for scrubbing the T-shirt.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 0,
    seed: 11234,
  },
  {
    filename:
      "samples/0001_p003-packing_016/1_p003-packing_016_g2_5_s1_Reach_for_the_clothes_brush_to_get_ready_for_scrubbing_the_T-shirt_.jsonl",
    scene: "p003-packing",
    sequence: "016",
    text: "Reach for the clothes brush to get ready for scrubbing the T-shirt.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 1,
    seed: 11234,
  },
  {
    filename:
      "samples/0001_p003-packing_016/1_p003-packing_016_g2_5_s2_Reach_for_the_clothes_brush_to_get_ready_for_scrubbing_the_T-shirt_.jsonl",
    scene: "p003-packing",
    sequence: "016",
    text: "Reach for the clothes brush to get ready for scrubbing the T-shirt.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 2,
    seed: 11234,
  },
  {
    filename:
      "samples/0002_p005-instrument-makeup-dog-packing-massage-firstaid-cleaning-tool_072/2_p005-instrument-makeup-dog-packing-massage-firstaid-cleaning-tool_072_g2_5_s0_Set_the_triangle_down_on_the_surface_.jsonl",
    scene: "p005-instrument-makeup-dog-packing-massage-firstaid-cleaning-tool",
    sequence: "072",
    text: "Set the triangle down on the surface.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 0,
    seed: 21234,
  },
  {
    filename:
      "samples/0002_p005-instrument-makeup-dog-packing-massage-firstaid-cleaning-tool_072/2_p005-instrument-makeup-dog-packing-massage-firstaid-cleaning-tool_072_g2_5_s1_Set_the_triangle_down_on_the_surface_.jsonl",
    scene: "p005-instrument-makeup-dog-packing-massage-firstaid-cleaning-tool",
    sequence: "072",
    text: "Set the triangle down on the surface.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 1,
    seed: 21234,
  },
  {
    filename:
      "samples/0002_p005-instrument-makeup-dog-packing-massage-firstaid-cleaning-tool_072/2_p005-instrument-makeup-dog-packing-massage-firstaid-cleaning-tool_072_g2_5_s2_Set_the_triangle_down_on_the_surface_.jsonl",
    scene: "p005-instrument-makeup-dog-packing-massage-firstaid-cleaning-tool",
    sequence: "072",
    text: "Set the triangle down on the surface.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 2,
    seed: 21234,
  },
  {
    filename:
      "samples/0003_p005-knitting-tablet_032/3_p005-knitting-tablet_032_g2_5_s0_Hold_the_tablet_like_a_steering_wheel_to_play_the_car_racing_game.jsonl",
    scene: "p005-knitting-tablet",
    sequence: "032",
    text: "Hold the tablet like a steering wheel to play the car racing game",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 0,
    seed: 31234,
  },
  {
    filename:
      "samples/0003_p005-knitting-tablet_032/3_p005-knitting-tablet_032_g2_5_s1_Hold_the_tablet_like_a_steering_wheel_to_play_the_car_racing_game.jsonl",
    scene: "p005-knitting-tablet",
    sequence: "032",
    text: "Hold the tablet like a steering wheel to play the car racing game",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 1,
    seed: 31234,
  },
  {
    filename:
      "samples/0003_p005-knitting-tablet_032/3_p005-knitting-tablet_032_g2_5_s2_Hold_the_tablet_like_a_steering_wheel_to_play_the_car_racing_game.jsonl",
    scene: "p005-knitting-tablet",
    sequence: "032",
    text: "Hold the tablet like a steering wheel to play the car racing game",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 2,
    seed: 31234,
  },
  {
    filename:
      "samples/0004_p005-plant-mindmap_051/4_p005-plant-mindmap_051_g2_5_s0_Turn_to_the_back_of_the_book_you_have_been_reading_to_verify_the_ISBN_number_.jsonl",
    scene: "p005-plant-mindmap",
    sequence: "051",
    text: "Turn to the back of the book you have been reading to verify the ISBN number.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 0,
    seed: 41234,
  },
  {
    filename:
      "samples/0004_p005-plant-mindmap_051/4_p005-plant-mindmap_051_g2_5_s1_Turn_to_the_back_of_the_book_you_have_been_reading_to_verify_the_ISBN_number_.jsonl",
    scene: "p005-plant-mindmap",
    sequence: "051",
    text: "Turn to the back of the book you have been reading to verify the ISBN number.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 1,
    seed: 41234,
  },
  {
    filename:
      "samples/0004_p005-plant-mindmap_051/4_p005-plant-mindmap_051_g2_5_s2_Turn_to_the_back_of_the_book_you_have_been_reading_to_verify_the_ISBN_number_.jsonl",
    scene: "p005-plant-mindmap",
    sequence: "051",
    text: "Turn to the back of the book you have been reading to verify the ISBN number.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 2,
    seed: 41234,
  },
  {
    filename:
      "samples/0005_p005-sandwich-salad-baking-monoply-boxing_238/5_p005-sandwich-salad-baking-monoply-boxing_238_g2_5_s0_Disconnect_the_pump_nozzle_from_the_air_valve_on_the_boxing_bag_when_the_bag_is_comp.jsonl",
    scene: "p005-sandwich-salad-baking-monoply-boxing",
    sequence: "238",
    text: "Disconnect the pump nozzle from the air valve on the boxing bag when the bag is completely inflated.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 0,
    seed: 51234,
  },
  {
    filename:
      "samples/0005_p005-sandwich-salad-baking-monoply-boxing_238/5_p005-sandwich-salad-baking-monoply-boxing_238_g2_5_s1_Disconnect_the_pump_nozzle_from_the_air_valve_on_the_boxing_bag_when_the_bag_is_comp.jsonl",
    scene: "p005-sandwich-salad-baking-monoply-boxing",
    sequence: "238",
    text: "Disconnect the pump nozzle from the air valve on the boxing bag when the bag is completely inflated.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 1,
    seed: 51234,
  },
  {
    filename:
      "samples/0005_p005-sandwich-salad-baking-monoply-boxing_238/5_p005-sandwich-salad-baking-monoply-boxing_238_g2_5_s2_Disconnect_the_pump_nozzle_from_the_air_valve_on_the_boxing_bag_when_the_bag_is_comp.jsonl",
    scene: "p005-sandwich-salad-baking-monoply-boxing",
    sequence: "238",
    text: "Disconnect the pump nozzle from the air valve on the boxing bag when the bag is completely inflated.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 2,
    seed: 51234,
  },
  {
    filename:
      "samples/0006_p007-laptop_003/6_p007-laptop_003_g2_5_s0_Insert_the_USB_of_the_Bluetooth_mouse_into_the_laptop.jsonl",
    scene: "p007-laptop",
    sequence: "003",
    text: "Insert the USB of the Bluetooth mouse into the laptop",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 0,
    seed: 61234,
  },
  {
    filename:
      "samples/0006_p007-laptop_003/6_p007-laptop_003_g2_5_s1_Insert_the_USB_of_the_Bluetooth_mouse_into_the_laptop.jsonl",
    scene: "p007-laptop",
    sequence: "003",
    text: "Insert the USB of the Bluetooth mouse into the laptop",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 1,
    seed: 61234,
  },
  {
    filename:
      "samples/0006_p007-laptop_003/6_p007-laptop_003_g2_5_s2_Insert_the_USB_of_the_Bluetooth_mouse_into_the_laptop.jsonl",
    scene: "p007-laptop",
    sequence: "003",
    text: "Insert the USB of the Bluetooth mouse into the laptop",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 2,
    seed: 61234,
  },
  {
    filename:
      "samples/0007_p007-tablet-gopro_163/7_p007-tablet-gopro_163_g2_5_s0_Turn_the_screw_tighter_using_a_screwdriver_to_ensure_a_secure_connection_.jsonl",
    scene: "p007-tablet-gopro",
    sequence: "163",
    text: "Turn the screw tighter using a screwdriver to ensure a secure connection.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 0,
    seed: 71234,
  },
  {
    filename:
      "samples/0007_p007-tablet-gopro_163/7_p007-tablet-gopro_163_g2_5_s1_Turn_the_screw_tighter_using_a_screwdriver_to_ensure_a_secure_connection_.jsonl",
    scene: "p007-tablet-gopro",
    sequence: "163",
    text: "Turn the screw tighter using a screwdriver to ensure a secure connection.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 1,
    seed: 71234,
  },
  {
    filename:
      "samples/0007_p007-tablet-gopro_163/7_p007-tablet-gopro_163_g2_5_s2_Turn_the_screw_tighter_using_a_screwdriver_to_ensure_a_secure_connection_.jsonl",
    scene: "p007-tablet-gopro",
    sequence: "163",
    text: "Turn the screw tighter using a screwdriver to ensure a secure connection.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 2,
    seed: 71234,
  },
  {
    filename:
      "samples/0008_p010-tea_009/8_p010-tea_009_g2_5_s0_Return_the_lid_to_the_teapot_to_cover_it_.jsonl",
    scene: "p010-tea",
    sequence: "009",
    text: "Return the lid to the teapot to cover it.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 0,
    seed: 81234,
  },
  {
    filename:
      "samples/0008_p010-tea_009/8_p010-tea_009_g2_5_s1_Return_the_lid_to_the_teapot_to_cover_it_.jsonl",
    scene: "p010-tea",
    sequence: "009",
    text: "Return the lid to the teapot to cover it.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 1,
    seed: 81234,
  },
  {
    filename:
      "samples/0008_p010-tea_009/8_p010-tea_009_g2_5_s2_Return_the_lid_to_the_teapot_to_cover_it_.jsonl",
    scene: "p010-tea",
    sequence: "009",
    text: "Return the lid to the teapot to cover it.",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 2,
    seed: 81234,
  },
  {
    filename:
      "samples/0009_p012-tablet_141/9_p012-tablet_141_g2_5_s0_Open_the_earphone_case_to_reveal_the_earphones.jsonl",
    scene: "p012-tablet",
    sequence: "141",
    text: "Open the earphone case to reveal the earphones",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 0,
    seed: 91234,
  },
  {
    filename:
      "samples/0009_p012-tablet_141/9_p012-tablet_141_g2_5_s1_Open_the_earphone_case_to_reveal_the_earphones.jsonl",
    scene: "p012-tablet",
    sequence: "141",
    text: "Open the earphone case to reveal the earphones",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 1,
    seed: 91234,
  },
  {
    filename:
      "samples/0009_p012-tablet_141/9_p012-tablet_141_g2_5_s2_Open_the_earphone_case_to_reveal_the_earphones.jsonl",
    scene: "p012-tablet",
    sequence: "141",
    text: "Open the earphone case to reveal the earphones",
    source: "unseen",
    guidance: 2.5,
    sample_idx: 2,
    seed: 91234,
  },
];
export default FILE_LIST;
